# Generated by Django 5.0.11 on 2026-08-30 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='idCategoria', primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(db_column='nombreCategoria', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='ConceptoGasto',
            fields=[
                ('id_concepto', models.AutoField(db_column='idConcepto', primary_key=True, serialize=False)),
                ('nombre_gasto', models.CharField(db_column='nombreGasto', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'conceptoGasto',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle_venta', models.AutoField(db_column='idDetalleVenta', primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(db_column='cantidad')),
                ('precio', models.DecimalField(db_column='precio', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'detalleVenta',
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id_entrada', models.AutoField(db_column='idEntrada', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='fecha')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fechaRegistro')),
            ],
            options={
                'db_table': 'entrada',
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id_forma_pago', models.AutoField(db_column='idFormaPago', primary_key=True, serialize=False)),
                ('forma_pago', models.CharField(db_column='formaPago', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'formaPago',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(db_column='idMarca', primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(db_column='nombreMarca', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(db_column='idPermiso', primary_key=True, serialize=False)),
                ('nombre_permiso', models.CharField(db_column='nombrePermiso', max_length=50)),
                ('modulo', models.CharField(db_column='modulo', max_length=50)),
            ],
            options={
                'db_table': 'permiso',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('costo', models.DecimalField(blank=True, db_column='costo', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(db_column='idRol', primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(db_column='nombreRol', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'rolPermiso',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_documento', models.AutoField(db_column='idTipoDocumento', primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(db_column='tipoDocumento', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipoDocumento',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(db_column='nombreUsuario', max_length=100)),
                ('email', models.EmailField(db_column='email', max_length=100, unique=True)),
                ('username', models.CharField(db_column='username', max_length=50, unique=True)),
                ('password_hash', models.CharField(db_column='passwordHash', max_length=255)),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fechaCreacion')),
                ('ultimo_acceso', models.DateTimeField(blank=True, db_column='ultimoAcceso', null=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(db_column='idVehiculo', primary_key=True, serialize=False)),
                ('anio', models.PositiveSmallIntegerField(db_column='anio')),
                ('patente', models.CharField(blank=True, db_column='patente', max_length=10, null=True, unique=True)),
            ],
            options={
                'db_table': 'vehiculo',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(db_column='idVenta', primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(db_column='fechaVenta')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fechaRegistro')),
            ],
            options={
                'db_table': 'venta',
            },
        ),
        migrations.CreateModel(
            name='DetalleEntrada',
            fields=[
                ('id_detalle_entrada', models.AutoField(db_column='idDetalleEntrada', primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(db_column='cantidad')),
                ('entrada', models.ForeignKey(db_column='idEntrada', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.entrada')),
            ],
            options={
                'db_table': 'detalleEntrada',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id_gasto', models.AutoField(db_column='idGasto', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='fecha')),
                ('monto', models.DecimalField(db_column='monto', decimal_places=2, max_digits=10)),
                ('observaciones', models.CharField(blank=True, db_column='observaciones', max_length=200, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fechaRegistro')),
                ('concepto', models.ForeignKey(db_column='idConcepto', on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='inventario.conceptogasto')),
            ],
            options={
                'db_table': 'gasto',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id_modelo', models.AutoField(db_column='idModelo', primary_key=True, serialize=False)),
                ('nombre_modelo', models.CharField(db_column='nombreModelo', max_length=50)),
                ('marca', models.ForeignKey(db_column='idMarca', on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='inventario.marca')),
            ],
            options={
                'db_table': 'modelo',
            },
        ),
        migrations.AddConstraint(
            model_name='permiso',
            constraint=models.UniqueConstraint(fields=('modulo', 'nombre_permiso'), name='uq_permiso_modulo_nombre'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(db_column='idCategoria', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoria'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='detalleentrada',
            name='producto',
            field=models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_entrada', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='rolpermiso',
            name='permiso',
            field=models.ForeignKey(db_column='idPermiso', on_delete=django.db.models.deletion.CASCADE, related_name='rol_permisos', to='inventario.permiso'),
        ),
        migrations.AddField(
            model_name='rolpermiso',
            name='rol',
            field=models.ForeignKey(db_column='idRol', on_delete=django.db.models.deletion.CASCADE, related_name='rol_permisos', to='inventario.rol'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(db_column='idRol', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='inventario.rol'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='usuario',
            field=models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='inventario.usuario'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='usuario',
            field=models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='inventario.usuario'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='modelo',
            field=models.ForeignKey(db_column='idModelo', on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='inventario.modelo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='vehiculo',
            field=models.ForeignKey(db_column='idVehiculo', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.vehiculo'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='vehiculo',
            field=models.ForeignKey(db_column='idVehiculo', on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='inventario.vehiculo'),
        ),
        migrations.AddField(
            model_name='venta',
            name='forma_pago',
            field=models.ForeignKey(db_column='idFormaPago', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='inventario.formapago'),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_documento',
            field=models.ForeignKey(db_column='idTipoDocumento', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='inventario.tipodocumento'),
        ),
        migrations.AddField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='inventario.usuario'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(db_column='idVenta', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.venta'),
        ),
        migrations.AddConstraint(
            model_name='modelo',
            constraint=models.UniqueConstraint(fields=('marca', 'nombre_modelo'), name='uq_modelo_marca_nombre'),
        ),
        migrations.AddConstraint(
            model_name='rolpermiso',
            constraint=models.UniqueConstraint(fields=('rol', 'permiso'), name='uq_rolpermiso_rol_permiso'),
        ),
    ]
