# Generated by Django 6.1 on 2026-09-02 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='forma_pago',
            field=models.ForeignKey(db_column='idFormaPago', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='inventario.formapago'),
            preserve_default=False,
        ),
    ]
