# Generated by Django 6.1 on 2026-09-05 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_gasto_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='imagen',
            field=models.ImageField(blank=True, db_column='imagen', null=True, upload_to='gastos/comprobantes/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='numero_documento',
            field=models.CharField(blank=True, db_column='numeroDocumento', max_length=50),
        ),
        migrations.AddField(
            model_name='gasto',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, db_column='idTipoDocumento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='inventario.tipodocumento'),
        ),
    ]
