# Generated by Django 6.1 on 2026-08-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_seed_permisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='tipo_documento',
            field=models.CharField(choices=[('NINGUNO', 'Ningún documento'), ('BOLETA', 'Boleta'), ('FACTURA', 'Factura')], db_column='tipoDocumento', default='NINGUNO', max_length=10),
        ),
    ]
