# Generated by Django 6.1 on 2026-09-05 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_gasto_imagen_gasto_numero_documento_and_more'),
        ('inventario', '0004_producto_soft_delete'),
    ]

    operations = [
    ]
