# Generated by Django 6.1 on 2026-09-06 16:42

from django.db import migrations, models


def poblar_codigos(apps, schema_editor):
    """Asigna PRD-{id:06d} a los productos que ya existian sin codigo."""
    Producto = apps.get_model('inventario', 'Producto')
    for producto in Producto.objects.filter(codigo__isnull=True):
        producto.codigo = f"PRD-{producto.pk:06d}"
        producto.save(update_fields=['codigo'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_merge_20260905_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, db_column='codigo', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(blank=True, db_column='precioVenta', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RunPython(poblar_codigos, migrations.RunPython.noop),
    ]
