# Generated by Django 6.1 on 2026-09-07 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_producto_codigo_producto_precio_venta'),
        ('inventario', '0006_seed_permisos_ventas'),
    ]

    operations = [
    ]
