# Generated by Django 6.1 on 2026-09-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_seed_permisos_ingresos'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(blank=True, db_column='tipo', help_text='Tipo de vehiculo (texto libre): automovil, camioneta, SUV, etc.', max_length=50),
        ),
    ]
