# Generated by Django 6.1 on 2026-09-07 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_merge_20260906_2213'),
        ('inventario', '0011_seed_permiso_importar_catalogo'),
    ]

    operations = [
    ]
