# Generated by Django 6.1 on 2026-09-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_merge_20260907_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, db_column='foto', null=True, upload_to='productos/%Y/%m/'),
        ),
    ]
