# Generated by Django 6.1 on 2026-09-08 16:23

import django.db.models.deletion
import inventario.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_producto_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoFoto',
            fields=[
                ('id_foto', models.AutoField(db_column='idFoto', primary_key=True, serialize=False)),
                ('imagen', models.ImageField(db_column='imagen', upload_to=inventario.models.ruta_foto_producto)),
                ('es_principal', models.BooleanField(db_column='esPrincipal', default=False)),
                ('orden', models.PositiveSmallIntegerField(db_column='orden', default=0)),
                ('ancho_px', models.PositiveSmallIntegerField(blank=True, db_column='anchoPx', null=True)),
                ('alto_px', models.PositiveSmallIntegerField(blank=True, db_column='altoPx', null=True)),
                ('peso_bytes', models.PositiveIntegerField(blank=True, db_column='pesoBytes', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creadoEn')),
                ('creado_por', models.ForeignKey(blank=True, db_column='creadoPor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_producto_creadas', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='inventario.producto')),
            ],
            options={
                'db_table': 'productoFoto',
                'ordering': ['orden', 'id_foto'],
                'indexes': [models.Index(fields=['producto', 'es_principal'], name='productoFot_idProdu_0f49e3_idx'), models.Index(fields=['producto', 'orden'], name='productoFot_idProdu_efd3b6_idx')],
            },
        ),
    ]
