# Generated by Django 6.1 on 2026-09-09 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_migrar_foto_producto_a_productofoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoInicial',
            fields=[
                ('id_saldo_inicial', models.AutoField(db_column='idSaldoInicial', primary_key=True, serialize=False)),
                ('monto', models.DecimalField(db_column='monto', decimal_places=2, max_digits=12)),
                ('fecha', models.DateField(db_column='fecha')),
                ('observaciones', models.CharField(blank=True, db_column='observaciones', max_length=200, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='fechaActualizacion')),
                ('usuario', models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saldos_iniciales_editados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saldoInicial',
            },
        ),
    ]
