# Generated by Django 6.1 on 2026-09-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_saldoinicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='monto_iva',
            field=models.DecimalField(blank=True, db_column='montoIva', decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_neto',
            field=models.DecimalField(blank=True, db_column='montoNeto', decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_total',
            field=models.DecimalField(blank=True, db_column='montoTotal', decimal_places=2, max_digits=12, null=True),
        ),
    ]
