# Generated by Django 6.1 on 2026-09-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_venta_montos_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='precio_estimado',
            field=models.DecimalField(blank=True, db_column='precioEstimado', decimal_places=2, max_digits=10, null=True),
        ),
    ]
