# Generated by Django 6.1 on 2026-09-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_detalleventa_precio_estimado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='observaciones',
            field=models.CharField(blank=True, db_column='observaciones', max_length=200, null=True),
        ),
    ]
