# Generated by Django 6.1 on 2026-09-13

from django.db import migrations


class Migration(migrations.Migration):
    """Une las dos ramas de migraciones incorporadas durante el merge."""

    dependencies = [
        ("inventario", "0003_entrada_tipo_documento"),
        ("inventario", "0020_seed_permisos_categorias"),
    ]

    operations = []
